"""initial tables

Revision ID: 7338a2aa871f
Revises: 
Create Date: 2026-03-15 14:08:54.431333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7338a2aa871f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('gns3_user_id', sa.String(length=64), nullable=False),
    sa.Column('gns3_username', sa.String(length=128), nullable=False),
    sa.Column('gns3_password_hash', sa.String(length=256), nullable=False),
    sa.Column('gns3_project_id', sa.String(length=64), nullable=False),
    sa.Column('student_user_id', sa.String(length=128), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'CLOSED', name='sessionstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_student_user_id'), 'sessions', ['student_user_id'], unique=False)
    op.create_table('history_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=128), nullable=False),
    sa.Column('component_id', sa.String(length=64), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_history_events_session_id'), 'history_events', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_history_events_session_id'), table_name='history_events')
    op.drop_table('history_events')
    op.drop_index(op.f('ix_sessions_student_user_id'), table_name='sessions')
    op.drop_table('sessions')
    # ### end Alembic commands ###
