"""behavioral_events table

Revision ID: e37ebf363a30
Revises: be307b53177b
Create Date: 2026-05-28 14:00:23.073874
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'e37ebf363a30'
down_revision: Union[str, None] = 'be307b53177b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('behavioral_events',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('lab_slug', sa.String(length=255), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('component_id', sa.String(length=255), nullable=True),
    sa.Column('component_type', sa.String(length=100), nullable=True),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('raw_command', sa.Text(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lab_slug'], ['labs.slug'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['learning_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_behavioral_events_session_ts', 'behavioral_events', ['session_id', 'timestamp'], unique=False)
    op.create_index('ix_behavioral_events_session_type', 'behavioral_events', ['session_id', 'event_type'], unique=False)
    op.create_index('ix_behavioral_events_user_lab', 'behavioral_events', ['user_id', 'lab_slug'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_behavioral_events_user_lab', table_name='behavioral_events')
    op.drop_index('ix_behavioral_events_session_type', table_name='behavioral_events')
    op.drop_index('ix_behavioral_events_session_ts', table_name='behavioral_events')
    op.drop_table('behavioral_events')
    # ### end Alembic commands ###
